In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[4, 1, 1, 4],
       [4, 7, 4, 6],
       [1, 3, 6, 5]])

In [4]:
arr.reshape(2,6)

array([[4, 1, 1, 4, 4, 7],
       [4, 6, 1, 3, 6, 5]])

In [5]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [7]:
arr.reshape(2,-1)

array([[4, 1, 1, 4, 4, 7],
       [4, 6, 1, 3, 6, 5]])

In [9]:
arr.T #transpose the matrix

array([[4, 4, 1],
       [1, 7, 3],
       [1, 4, 6],
       [4, 6, 5]])

In [10]:
arr.flatten()  # it is matrix in one line

array([4, 1, 1, 4, 4, 7, 4, 6, 1, 3, 6, 5])

In [11]:
arr1 =np.array([1,2,3,4,5])

In [13]:
arr1.ndim

1

In [14]:
np.expand_dims(arr1,axis =1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
np.expand_dims(arr1,axis =0)

array([[1, 2, 3, 4, 5]])

In [16]:
np.expand_dims(arr1,axis =2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [17]:
arr

array([[4, 1, 1, 4],
       [4, 7, 4, 6],
       [1, 3, 6, 5]])

In [18]:
np.squeeze(arr)

array([[4, 1, 1, 4],
       [4, 7, 4, 6],
       [1, 3, 6, 5]])

In [19]:
data =np.array([[1],[2],[3]])

In [20]:
data

array([[1],
       [2],
       [3]])

In [21]:
np.ndim(data)

2

In [22]:
np.squeeze(data)

array([1, 2, 3])

In [23]:
arr1

array([1, 2, 3, 4, 5])

In [24]:
np.repeat(arr1,3) #repeat data

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [25]:
np.roll(arr1,2)   

array([4, 5, 1, 2, 3])

In [27]:
np.diag(arr1) #diagonal form

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
#Numpy - binary operator

In [30]:
arr1 = np.random.randint(1,10,(3,4))

In [31]:
arr2= np.random.randint(1,10,(3,4))

In [32]:
arr1 + arr2

array([[16,  7, 14, 15],
       [ 7,  9, 15,  8],
       [ 3,  9, 16,  8]])