In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
l = [1,2,3,4]

In [5]:
ar = np.array(l) #list into array

In [6]:
ar # one dimension

array([1, 2, 3, 4])

In [7]:
type(ar)

numpy.ndarray

In [9]:
np.array([[1,2],[3,4]]) #two dimension

array([[1, 2],
       [3, 4]])

In [10]:
np.asarray(l)

array([1, 2, 3, 4])

In [11]:
a = [2,3,4,]

In [12]:
np.asanyarray(a)

array([2, 3, 4])

In [17]:
b = np.matrix(l) #matrix is two dimension & subset of array

In [18]:
b

matrix([[1, 2, 3, 4]])

In [19]:
a = np.asarray(l)

In [20]:
a

array([1, 2, 3, 4])

In [21]:
c = a  #solo copy

In [22]:
c

array([1, 2, 3, 4])

In [23]:
a

array([1, 2, 3, 4])

In [24]:
c[0] = 100

In [25]:
c

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [29]:
d = np.copy(a)   #deep copy

In [30]:
d

array([100,   2,   3,   4])

In [31]:
a[1] = 400

In [32]:
a 

array([100, 400,   3,   4])

In [33]:
d

array([100,   2,   3,   4])

In [34]:
np.fromfunction(lambda i , j: i==j,(3,3)) #genrate the data

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i , j: i*j,(3,3)) #genrate the data

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [36]:
iterable = (i*i for i in range(5)) #iterable also create array

In [37]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [39]:
np.fromstring('112 212', sep = ' ') #seprater 

array([112., 212.])

In [43]:
np.fromstring('128, 212', sep = ', ') #seprater 

array([128., 212.])

In [44]:
#Numpy - datatype

In [45]:
l = [2,3,4,5,6]

In [46]:
ar = np.array(l)

In [47]:
ar

array([2, 3, 4, 5, 6])

In [50]:
ar.ndim  #know about dimension of array

1

In [57]:
ar2= np.array([[2,1,3,1,3,4],[271,5,7,127,133,1]])

In [58]:
ar2

array([[  2,   1,   3,   1,   3,   4],
       [271,   5,   7, 127, 133,   1]])

In [59]:
ar2.ndim

2

In [60]:
ar2.size

12

In [61]:
ar2.shape

(2, 6)

In [62]:
ar2.dtype

dtype('int64')

In [63]:
list(range(5))

[0, 1, 2, 3, 4]

In [64]:
np.arange(0.1,5)

array([0.1, 1.1, 2.1, 3.1, 4.1])

In [67]:
list(np.arange(0.1,5,.6))

[0.1, 0.7, 1.3, 1.9, 2.5, 3.1, 3.6999999999999997, 4.3, 4.8999999999999995]

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.linspace(2,4,20) #produce data between 2 to 4

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [62]:
np.logspace #find log like linspace

<function logspace at 0x719f74104d30>

In [63]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [59]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.empty((1,2)) # create empty array

array([[5.43230922e-312, 7.29112202e-304]])

In [65]:
#create data random  
np.random.randn(2,3)

array([[-0.61102821,  0.24597679, -0.01256193],
       [ 0.92569434, -1.65883479,  0.18784684]])

In [66]:
#create data random  
arr =np.random.randn(2,3)

In [67]:
import pandas as pd


In [68]:
pd.DataFrame(arr)

0         1         2
0 -0.336958  0.887194  0.209187
1 -0.034733  2.676910  1.607642

In [71]:
np.random.rand(2,3) #normal data produce

array([[0.16364669, 0.71557908, 0.95270847],
       [0.03519743, 0.1276625 , 0.20303698]])

In [73]:
np.random.randint(1,99,(4,6,2))

array([[[41, 34],
        [37, 76],
        [67, 70],
        [81, 57],
        [37, 58],
        [77, 70]],

       [[33, 67],
        [32, 45],
        [27, 16],
        [74, 28],
        [39, 41],
        [63, 93]],

       [[25, 41],
        [49, 26],
        [49, 96],
        [80, 10],
        [35, 68],
        [62, 85]],

       [[16, 82],
        [60, 45],
        [ 8, 87],
        [94, 89],
        [81, 53],
        [98, 33]]])

In [78]:
np.random.randint(1,99,(4,6,2))

array([[[24, 74],
        [65, 12],
        [86, 57],
        [25, 14],
        [ 7, 50],
        [17, 93]],

       [[37, 79],
        [ 1, 16],
        [39, 49],
        [40, 84],
        [50, 68],
        [58, 78]],

       [[63, 10],
        [ 9, 42],
        [18, 91],
        [41, 28],
        [52, 88],
        [91, 73]],

       [[48, 79],
        [81,  2],
        [73, 19],
        [61, 42],
        [69, 13],
        [ 4, 97]]])

In [81]:
pd.DataFrame(np.random.randint(1,99,(200,500))).to_csv('RR.csv')

In [82]:
pk = np.random.rand(3,4)

In [83]:
pk

array([[0.16761288, 0.57255757, 0.29867074, 0.46730205],
       [0.79560424, 0.55975917, 0.93839435, 0.07964625],
       [0.79098088, 0.25896275, 0.78918914, 0.25140859]])

In [84]:
pk.reshape(6,4)

ValueError: cannot reshape array of size 12 into shape (6,4)

In [85]:
pk.reshape(6,-1)

array([[0.16761288, 0.57255757],
       [0.29867074, 0.46730205],
       [0.79560424, 0.55975917],
       [0.93839435, 0.07964625],
       [0.79098088, 0.25896275],
       [0.78918914, 0.25140859]])

In [86]:
pk1 = pk.reshape(6,-1)

In [87]:
pk1

array([[0.16761288, 0.57255757],
       [0.29867074, 0.46730205],
       [0.79560424, 0.55975917],
       [0.93839435, 0.07964625],
       [0.79098088, 0.25896275],
       [0.78918914, 0.25140859]])

In [89]:
pk1[1]

array([0.29867074, 0.46730205])

In [90]:
pk1[1][1]

0.4673020502278735

In [91]:
pk1[2:5,1]

array([0.55975917, 0.07964625, 0.25896275])

In [92]:
ak3 = np.random.randint(1,120,(5,6))

In [93]:
ak3

array([[109,  98,  99,  99,  81,  40],
       [ 58, 113,  79, 116, 104, 116],
       [ 85,  26,  59,  83,  32,   8],
       [ 30,  26,  56, 100,  34,  55],
       [ 31,  67,  59,  65, 119,  38]])

In [99]:
[ak3>50]

[array([[ True,  True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True,  True],
        [ True, False,  True,  True, False, False],
        [False, False,  True,  True, False,  True],
        [False,  True,  True,  True,  True, False]])]

In [100]:
ak3[ak3>80]

array([109,  98,  99,  99,  81, 113, 116, 104, 116,  85,  83, 100, 119])

In [101]:
ak3

array([[109,  98,  99,  99,  81,  40],
       [ 58, 113,  79, 116, 104, 116],
       [ 85,  26,  59,  83,  32,   8],
       [ 30,  26,  56, 100,  34,  55],
       [ 31,  67,  59,  65, 119,  38]])