In [1]:
#sort ,Search & counting Functions.

In [2]:
import numpy as np 

In [3]:
arr =np.array([4,3,5,3,4,53,8,5,21,3,2,4,35,1])

In [4]:
arr

array([ 4,  3,  5,  3,  4, 53,  8,  5, 21,  3,  2,  4, 35,  1])

In [5]:
np.sort(arr) #sort  the data

array([ 1,  2,  3,  3,  3,  4,  4,  4,  5,  5,  8, 21, 35, 53])

In [6]:
np.searchsorted(arr,20)

14

In [7]:
arr1 = np.array([0,34,563,2,56,3,0,267,1,0,0])

In [8]:
np.count_nonzero(arr1) # find non zero data

7

In [9]:
arr

array([ 4,  3,  5,  3,  4, 53,  8,  5, 21,  3,  2,  4, 35,  1])

In [10]:
np.where(arr > 6)

(array([ 5,  6,  8, 12]),)

In [11]:
np.extract(arr > 3 ,arr)

array([ 4,  5,  4, 53,  8,  5, 21,  4, 35])

In [12]:
#Numpy - byte swapping

In [13]:
arr.byteswap()

array([ 288230376151711744,  216172782113783808,  360287970189639680,
        216172782113783808,  288230376151711744, 3819052484010180608,
        576460752303423488,  360287970189639680, 1513209474796486656,
        216172782113783808,  144115188075855872,  288230376151711744,
       2522015791327477760,   72057594037927936])

In [14]:
#Numpy - copy & views

In [15]:
arr

array([ 4,  3,  5,  3,  4, 53,  8,  5, 21,  3,  2,  4, 35,  1])

In [16]:
a = np.copy(arr) #create a copy new location

In [17]:
b = arr.view() #not locatte another place

In [18]:
b

array([ 4,  3,  5,  3,  4, 53,  8,  5, 21,  3,  2,  4, 35,  1])

In [19]:
arr

array([ 4,  3,  5,  3,  4, 53,  8,  5, 21,  3,  2,  4, 35,  1])

In [20]:
b[0] = 67

In [21]:
b

array([67,  3,  5,  3,  4, 53,  8,  5, 21,  3,  2,  4, 35,  1])

In [22]:
arr

array([67,  3,  5,  3,  4, 53,  8,  5, 21,  3,  2,  4, 35,  1])

In [23]:
#Numpy - matrix libarary

In [28]:
import numpy.matlib as nm

In [29]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [30]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])